-- MySQL Script generated by MySQL Workbench
-- Sun Nov  5 16:06:16 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Da bi se inicijalizirala baza potrebno je ovaj dokument otvoriti u mysql workbench i pokrenuti

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bpTim11db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bpTim11db` ;

-- -----------------------------------------------------
-- Schema bpTim11db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bpTim11db` DEFAULT CHARACTER SET utf8 ;
USE `bpTim11db` ;

-- -----------------------------------------------------
-- Table `bpTim11db`.`uloge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bpTim11db`.`uloge` ;

CREATE TABLE IF NOT EXISTS `bpTim11db`.`uloge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpTim11db`.`korisnici`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bpTim11db`.`korisnici` ;

CREATE TABLE IF NOT EXISTS `bpTim11db`.`korisnici` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NULL,
  `prezime` VARCHAR(45) NULL,
  `uloga` INT NULL,
  INDEX `fk_korisnici_uloge_idx` (`uloga` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_korisnici_uloge`
    FOREIGN KEY (`uloga`)
    REFERENCES `bpTim11db`.`uloge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpTim11db`.`vidljivosti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bpTim11db`.`vidljivosti` ;

CREATE TABLE IF NOT EXISTS `bpTim11db`.`vidljivosti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bpTim11db`.`dokumenti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bpTim11db`.`dokumenti` ;

CREATE TABLE IF NOT EXISTS `bpTim11db`.`dokumenti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NULL,
  `fajl` BLOB NULL,
  `vlasnik` INT NULL,
  `vidljivost` INT NULL,
  INDEX `fk_dokumenti_korisnici1_idx` (`vlasnik` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_dokumenti_vidljivosti1_idx` (`vidljivost` ASC),
  CONSTRAINT `fk_dokumenti_korisnici1`
    FOREIGN KEY (`vlasnik`)
    REFERENCES `bpTim11db`.`korisnici` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dokumenti_vidljivosti1`
    FOREIGN KEY (`vidljivost`)
    REFERENCES `bpTim11db`.`vidljivosti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
GRANT USAGE ON *.* TO bpUser;
 DROP USER bpUser;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'bpUser' IDENTIFIED BY '1234ab';

GRANT ALL ON `bpTim11db`.* TO 'bpUser';
GRANT SELECT, INSERT, TRIGGER ON TABLE `bpTim11db`.* TO 'bpUser';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `bpTim11db`.* TO 'bpUser';
GRANT SELECT ON TABLE `bpTim11db`.* TO 'bpUser';


INSERT INTO bptim11db.uloge VALUES(naziv,'administrator'), (naziv,'management'), (naziv,'student'), (naziv,'studentska');
INSERT INTO bptim11db.vidljivosti VALUES(naziv,'svi'),(naziv,'management'),(naziv,'studentska'),(naziv,'studenti');

INSERT INTO `bptim11db`.`korisnici` (`ime`, `prezime`, `uloga`) VALUES ('Ajla', 'Alic', '1');
INSERT INTO `bptim11db`.`korisnici` (`ime`, `prezime`, `uloga`) VALUES ('Ena', 'Muratspahic', '1');
INSERT INTO `bptim11db`.`korisnici` (`ime`, `prezime`, `uloga`) VALUES ('Elvedin', 'Sinanovic', '1');


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
